export const cocktailActions = {
    UPDATE_CURRENT_DRINK: "UPDATE_CURRENT_DRINK",
    UPDATE_DRINK_SEARCH: "UPDATE_DRINK_SEARCH",
    ADD_COCKTAIL_SEARCH_TO_CACHE: "ADD_COCKTAIL_SEARCH_TO_CACHE",
    ADD_ADVANCED_COCKTAIL_SEARCH_TO_CACHE: "ADD_ADVANCED_COCKTAIL_SEARCH_TO_CACHE"
} as const;

export const searchType = {
    DEFAULT: "DEFAULT",
    ADVANCED: "ADVANCED"
} as const;
